language: node_js
node_js:
- 4.2.1
install:
- npm install -g babel
- npm install -g webpack
- npm install -g webpack-dev-server
- npm install -g eslint
- npm install
script:
- npm run test
notifications:
  email:
  - stollenwerk@kitconcept.com
