language: node_js
node_js:
- 4.4.5
env:
  - NODE_ENV=prod
  - NODE_ENV=dev
cache:
  directories:
    - node_modules
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - wget "http://chromedriver.storage.googleapis.com/2.22/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
- npm install -g babel
- npm install -g webpack
- npm install -g webpack-dev-server
- npm install -g eslint
- npm install -g protractor
- webdriver-manager update --standalone
- webdriver-manager start &
- npm install
- sudo pip install -r requirements.txt
script:
- npm run lint:travis
- npm run test
- pybot test.robot
- npm run test:acceptance

notifications:
  email:
  - stollenwerk@kitconcept.com
